version: "3.9"

services:
  app:
    build: .
    container_name: binance-notification-bot
    ports:
      - "9001:9001"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=${PORT}
      - URL_BINANCE=${URL_BINANCE}
      - TOKEN_TELEGRAM=${TOKEN_TELEGRAM}
      - CHAT_ID_TELEGRAM=${CHAT_ID_TELEGRAM}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MINIMUM_AMOUNT=${MINIMUM_AMOUNT}
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head && python main.py"
    networks:
      - binance-network

  db:
    image: postgres:16
    container_name: binance-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - binance-network

volumes:
  pgdata:

networks:
  binance-network:
    driver: bridge
