version: "3.9"

services:
  app:
    build: .
    container_name: binance-notification-bot
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_URL=${DATABASE_URL}
      - URL_BINANCE=${URL_BINANCE}
      - TOKEN_TELEGRAM=${TOKEN_TELEGRAM}
      - CHAT_ID_TELEGRAM=${CHAT_ID_TELEGRAM}

      # Agrega aquí otras variables de entorno necesarias
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: binance-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
