"""se modificó campo status

Revision ID: 050f8db5b3dd
Revises: 77ebf5eaacfa
Create Date: 2025-08-30 21:29:41.728000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050f8db5b3dd'
down_revision: Union[str, Sequence[str], None] = '77ebf5eaacfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
