"""modify decimal scale

Revision ID: 08e6a71b2410
Revises: d8f76722176c
Create Date: 2025-06-28 00:57:48.907776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e6a71b2410'
down_revision: Union[str, Sequence[str], None] = 'd8f76722176c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arbitration_ustd', 'trans_amount',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
    op.alter_column('arbitration_ustd', 'buy_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
    op.alter_column('arbitration_ustd', 'sell_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
    op.alter_column('arbitration_ustd', 'spread',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arbitration_ustd', 'spread',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('arbitration_ustd', 'sell_price',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('arbitration_ustd', 'buy_price',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('arbitration_ustd', 'trans_amount',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
