"""create table buy zone

Revision ID: 71599ba466a3
Revises: b789eb78c88e
Create Date: 2025-08-28 23:34:03.842820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71599ba466a3'
down_revision: Union[str, Sequence[str], None] = 'b789eb78c88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buy_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buy_zone_id'), 'buy_zone', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buy_zone_id'), table_name='buy_zone')
    op.drop_table('buy_zone')
    # ### end Alembic commands ###
