"""se agregó campo de status en buy_zone

Revision ID: 77ebf5eaacfa
Revises: 8887bb48ff4e
Create Date: 2025-08-30 19:29:36.057847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ebf5eaacfa'
down_revision: Union[str, Sequence[str], None] = '8887bb48ff4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_zone', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buy_zone', 'status')
    # ### end Alembic commands ###
