"""crear tabla arbitration_ustd

Revision ID: 83f3eb0e0ec3
Revises: 
Create Date: 2025-06-27 23:45:54.409186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f3eb0e0ec3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arbitration_ustd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('buy_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sell_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('spread', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('createAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arbitration_ustd_id'), 'arbitration_ustd', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arbitration_ustd_id'), table_name='arbitration_ustd')
    op.drop_table('arbitration_ustd')
    # ### end Alembic commands ###
