"""agrego-nicknames

Revision ID: bd9387da7e68
Revises: 08e6a71b2410
Create Date: 2025-06-30 22:28:15.801215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9387da7e68'
down_revision: Union[str, Sequence[str], None] = '08e6a71b2410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arbitration_ustd', sa.Column('buyer_nickname', sa.String(length=100), nullable=True))
    op.add_column('arbitration_ustd', sa.Column('seller_nickname', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arbitration_ustd', 'seller_nickname')
    op.drop_column('arbitration_ustd', 'buyer_nickname')
    # ### end Alembic commands ###
